### ISSUE TITLE
Add membership if doesn't exit

### ISSUE THREAD

**Issue by tarastrauss** [tarastrauss/chefs_hat#1]
I'm trying to add a member to one of my hats, but only if that user isn't already a member of the hat! I have an if else statement (if the user is already a member, flash an alert and re-render the page - otherwise add them as a member and re-render the page). I keep getting an issue saying that I have a double render :-(

![screen shot 2015-11-03 at 10 39 05 am](https://cloud.githubusercontent.com/assets/14189882/10917837/99c6862a-8217-11e5-9190-3b234ad7afb0.png)

![screen shot 2015-11-03 at 10 41 34 am](https://cloud.githubusercontent.com/assets/14189882/10917833/95c7ebd6-8217-11e5-8845-87b988b703de.png)

**Comment by tambling** [comment]
First of all: line 13 isn't syntactically correct.

Second of all: you're calling `redirect_to` once for each member– a controller action needs to have `render` or `redirect_to` once and only once. If you have an `if...else...`, you can have a `render`/`redirect_to` in each clause, because only one will be run.

**Comment by tarastrauss** [comment]
That's what's confusing me! the redirect_to is in an if else statement so isn't it only getting called once? If (a) then it gets called otherwise (b) and it gets called?

**Comment by tambling** [comment]
It's in an `each` block– it's getting called once per "`memeber`"

**Comment by tarastrauss** [comment]
omg THANK YOU!! It works and I totally see what I did wrong. :D

**Comment by tambling** [comment]
:pray:
